### ISSUE TITLE
will be using your pattern in next update

### ISSUE THREAD

**Issue by merl-dev** [ylxdzsw/RedisAlchemy.jl#1]
I will make a reference to your repo here, or post this as an issue in the Redis.jl repo. Enhances performance by 40%.  谢谢你！

```
const CRLF = "\r\n"
function sendCommand(conn::RedisConnection, cmdString)
    splits = split(cmdString, ' ')
    print(conn.socket, '*', length(splits), CRLF)
    for item in splits
        print(conn.socket, '$', sizeof(item), CRLF, item, CRLF)
    end
end
export sendCommand
```

**Comment by ylxdzsw** [comment]
Glad to hear that! Also thank you for your contributions to Redis.jl!

However, I feel nervous about `split(cmdString, ' ')`, as it may cause bug if value string contains space. for example, `set testkey "hello world!"` will be split into 4 parts, but it should be three.

**Comment by merl-dev** [comment]
Turns out I actually made an error and misinterpreted the benchmark results, it's actually far worse!  I guess I was tired (was like 4am), but the results were 'ms' for this approach vs nanoseconds for the original.  

On a bigger note, I found a comparison of Redis clients, Go, Ruby, C, Crystal, Java and Node.  It was quite poorly written and I think the writer, having written the Crystal client, actually cheated.  Nonetheless, the results were dramatically different.  See https://github.com/stefanwille/redis-client-benchmarks and the blog http://www.stefanwille.com/2015/05/redis-clients-crystal-vs-ruby-vs-c-vs-go/. 

I am now really curious to understand what makes Go tick so fast.

Even taking account the differences in the test routine run, our Julia package would have been one of the worst, whereas the libhiredis version, HiRedis.jl, would likely have been among the best.  So I continue to be convinced that there is a huge issue with Julia's IO implementation, possibly due to its dependence on libuv.  Node, which is also shares this dependency, was also ranked quite poorly. Since I am about to start a production implementation in the upcoming weeks, I believe I will look at merging the packages and filing an issue with julia-dev. 

Not sure what your use cases are, but I need spiffy performance and it seems that libhiredis is the only way to go for production implementations.

**Comment by merl-dev** [comment]
... I have a new PR with a streaming scan version, you might want to take a look.  Your comments are much appreciated.

**Comment by ylxdzsw** [comment]
I'm curious about why the origin approach could be faster, as string concatenations are relatively slow in julia. It allocates memories and copy data every time, thus also increases gc time. I may have missed some possible optimizations, but I think write arguments directly into socket is the right way.

I'm not using julia in production, and do not care much about it's performance. However, I will appreciate it if you make Redis in julia faster.

**Comment by ylxdzsw** [comment]
I tried some benchmark myself:

```
julia> @benchmark set(conn, "testkey", "Hello World!")
BenchmarkTools.Trial:
  samples:          10000
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  4.92 kb
  allocs estimate:  110
  minimum time:     48.95 μs (0.00% GC)
  median time:      73.03 μs (0.00% GC)
  mean time:        86.55 μs (0.77% GC)
  maximum time:     3.50 ms (95.25% GC)

julia> @benchmark resp_send(conn.socket, "set", "testkey", "Hello World!") |> resp_read
BenchmarkTools.Trial:
  samples:          10000
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  2.13 kb
  allocs estimate:  53
  minimum time:     150.80 μs (0.00% GC)
  median time:      235.28 μs (0.00% GC)
  mean time:        251.00 μs (0.21% GC)
  maximum time:     5.55 ms (94.39% GC)
```

It do seem that my version is much slower. However, I made a little change:

```
function resp_send(socket::TCPSocket, commands::ByteString...)
    socket << '*' << length(commands) << CRLF
    for command in commands
        socket << '$' << sizeof(command) << CRLF << command << CRLF
    end
    socket
end

function resp_send2(socket::TCPSocket, commands::ByteString...)
    a = IOBuffer()
    a << '*' << length(commands) << CRLF
    for command in commands
        a << '$' << sizeof(command) << CRLF << command << CRLF
    end
    write(socket, seekstart(a))
    socket
end
```

The result is VERY SURPRISING:

```
julia> @benchmark resp_send2(conn.socket, "set", "testkey", "Hello World!") |> resp_read
BenchmarkTools.Trial:
  samples:          10000
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  1.47 kb
  allocs estimate:  35
  minimum time:     30.00 μs (0.00% GC)
  median time:      41.84 μs (0.00% GC)
  mean time:        52.15 μs (0.00% GC)
  maximum time:     269.62 μs (0.00% GC)
```

I just print them into a buffer and write into socket in one invoke, and got a huge improvement. I guess Julia make new tasks every time writing to socket to make everything async (like node.js), and it causes much overhead of switching, locking and waiting.

**Comment by merl-dev** [comment]
Yes, that would explain the profiler results.  Both Node and Julia use libuv under-the-hood and therein could be one of the culprits, but since this isn't my specialty (yet) I have little to offer. 
As for the potential performance enhancement of using libhiredis, here is the best example:

## Pipeline test

set key 10^6 times and read reply

```
function pipeTest()
    for i=1:1000000
      set(pipe, "newkey", "abc")
    end
    result = read_pipeline(pipe)
end
```

**without libhiredis**

```
@benchmark pipeTest()
BenchmarkTools.Trial:
  samples:          1
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  4.39 gb
  allocs estimate:  99998018
  minimum time:     38.43 s (2.78% GC)
  median time:      38.43 s (2.78% GC)
  mean time:        38.43 s (2.78% GC)
  maximum time:     38.43 s (2.78% GC)
```

**performance ==> 26K writes per second**

**HiRedis**

```
function pipeTest()
    for i=1:1000000
       kvset("newkey, "abc", pipeline=true)
    end
    result = get_reply()
end
```

```
@benchmark pipeTest()
BenchmarkTools.Trial:
  samples:          3
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  237.87 mb
  allocs estimate:  5998998
  minimum time:     2.46 s (2.20% GC)
  median time:      2.46 s (2.52% GC)
  mean time:        2.46 s (2.46% GC)
  maximum time:     2.46 s (2.67% GC)
```

**performance ==> 406K writes per second**

I am just finishing up the libhiredis integration so I don't have the benchmark yet
